# Generated by Django 2.2.1 on 2019-05-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choose_text',
            new_name='choice_text',
        ),
    ]
